### PR TITLE
Add InClass exercises and solutions for JS2 Week1

### PR DESCRIPTION
**Pull request by makanti**
## What does this change?

Module: JS2
Week(s): 1

## Description
Adding solutions for JS2 Week 1 of Syllabus as per students' request.
Adds solutions in tabs using [Docusaurus tabs](https://docusaurus.io/docs/next/markdown-features/tabs)

## Who needs to know about this?

Hey @ChrisOwen101 @illicitonion, could you guys please review this PR so that I can give solutions to students who asked for it? Thanks! 🙏

### CODE REVIEW

**Comment by illicitonion** [comment]
The solutions look great, but I'm a little concerned about checking in a second copy of the exercises - it feels like it will be very easy for the exercises to get out of sync between the class page and the Exercises folder... I wonder if there's a way we can have the syllabus use some kind of `include` directive to reference the files in the Exercises folder... @ChrisOwen101 how's your docusaurus-fu?

**Comment by 40thieves** [comment]
> The solutions look great, but I'm a little concerned about checking in a second copy of the exercises - it feels like it will be very easy for the exercises to get out of sync between the class page and the Exercises folder

Heh, this is almost the same problem I was thinking about almost 2 years ago: https://github.com/CodeYourFuture/syllabus-archive/pull/251 😁 

---

As an alternative idea, we do now have the convention of providing coursework answers in repos named MODULE_NAME-Coursework-WEEK_NUMBER-Solution, for example: https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week1-Solution. We could consider putting the in-class exercise solutions in there too?

This wouldn't solve the problem of "content drift", but at least it would be a standardised place for students to look. I imagine/hope that trainees would flag up any mismatches too.

**Comment by makanti** [comment]
Hey guys, all valid points.  @40thieves on your repo suggestion, the problem will be that at the moment we don't give students access to [homework solutions](https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week1-Solution) before js2-week2 begins, as we want them to have a go first themselves. I reckon they will want to look at the inclass exercises during that first homework week though, and that's why I didn't add the solutions in there.

**Review by illicitonion — APPROVED** [review]
This looks beautiful, thanks!!

I'll merge now - I noticed Object Methods exercises 2 and 3 were missing - was that intentional/accidental/lack-of-time? :)

(Put another way: Do you have them sitting on your computer accidentally not committed, or should I put together some answers? :D)

**Comment by makanti** [comment]
Hey @illicitonion, sorry for the late response to this. Only exercises I skipped where the first ones which are a bit more abstract.. method ones should be there. Thanks for merging! 🙏

**Comment by SallyMcGrath** [comment]
@all-contributors please add @makanti for content and code

**Pull request merged**
