### PR TITLE
Fix Search on Syllabus (Remove Algolia)

### PR DESCRIPTION
**Pull request by ChrisOwen101**
## What does this change?

Module: All
Week(s): All

## Description

It was raised on Slack that Search has stopped working because of a reliance on Algolia which powers the search.

This PR fixes this by stopping our reliance on Algolia and changing to a search that runs at build time. It's a tiny bit slower but absolutely does the job.

## Who needs to know about this?

@SallyMcGrath

### CODE REVIEW

**Review by kfklein15 — DISMISSED** [review]
We need three reviewers right now, so am approving this too. Thanks, Chris!

**Review by SallyMcGrath — DISMISSED** [review]
LGTM -- no objection to lunr -- ta Chris!

**Review by SallyMcGrath — APPROVED** [review]
rote approval without check

**Comment by SallyMcGrath** [comment]
@ChrisOwen101 (it's not an emergency because it just doesn't deploy but it will block deploys) this build fails. 

I pulled down this PR before I approved and built it on my local. It was fine here. Can you take a look and see what is failing? I'll revert tomorrow if not so we don't block deploys. Ta!

**Comment by ChrisOwen101** [comment]
Eek sorry! Tested on my end and it worked as well.

I'll take a look when I get home later on this evening.

**Pull request merged**
