### PR TITLE
Update lesson.md

### PR DESCRIPTION
**Pull request by jcholyhead**
- 

## What does this change?
Module: SQL
Week(s): 3

## Description

Parameterised user input in reading data example. Previous example allowed SQL injection through the API query parameter.

## Who needs to know about this?

Syllabus team
## Rendered Pages

-----
[View rendered docs/db/week-3/lesson.md](https://github.com/jcholyhead/syllabus/blob/patch-1/docs/db/week-3/lesson.md)

### CODE REVIEW

**Comment by szemate** [comment]
While this change makes sense, I don't think we should put code like this into the examples without explanation. Anyway, this is not the only SQL command that allows SQL injection, almost all the code examples in the lesson do.

**Comment by jcholyhead** [comment]
> While this change makes sense, I don't think we should put code like this into the examples without explanation. Anyway, this is not the only SQL command that allows SQL injection, almost all the code examples in the lesson do.

I think this is the only string concatenation example in the lesson file (I haven't spotted any others). All the others use parameterised queries. Parameterising a LIKE clause is a little messy because of the wildcards, which is why I guess it was left in as a string concatenation.

**Comment by szemate** [comment]
> All the others use parameterised queries.

Yes you're right. I think it's good to merge then.

**Comment by szemate** [comment]
If no-one from the syllabus team has any objection, I will merge it today before 10 so that we have the fixed syllabus for today's class.

**Comment by SallyMcGrath** [comment]
@all-contributors please add @jcholyhead  for content and code

**Pull request merged**
