### PR TITLE
Contribution Guide Link Updates

### PR DESCRIPTION
**Pull request by ChrisOwen101**
## Description

Update the `CONTRIBUTION.md` so it goes to the right place. 
Update links to the contribution guide.

## Who needs to know about this?

#46 
@40thieves

### CODE REVIEW

**Review by alismith-dev — APPROVED** [review]
LGTM :shipit:

**Comment by 40thieves** [comment]
(Apologies if you already know this) Github has a magic keyword: if you put "Closes #46" in the description, then it auto-closes the issue when the PR is merged. https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by 40thieves** [comment]
Is there any content in the fundamentals contribution guide that should be moved? Otherwise I'd say that we should just remove it.

**Comment by ChrisOwen101** [comment]
Closes #46

**Pull request merged**
