### PR TITLE
Updating presentation

### PR DESCRIPTION
**Pull request by kfklein15**
Updating briefing presentation at the bottom

Signed-off-by: KFK <80272258+kfklein15@users.noreply.github.com>

## What does this change?

Module: Final Projects
Week(s): Preparation

## Description

Updating the briefing presentation with a new version

## Who needs to know about this?

 @AliciaE08 @martaesn @ShaunCYFSA @caromelendezl @emcglackenr1

### CODE REVIEW

**Review by SallyMcGrath — APPROVED** [review]
LGTM

BTW I have some minor comments on the slide deck, let me know where to leave them. I feel like I saw a slack post somewhere in the maelstrom...

**Comment by kfklein15** [comment]
Hey Sally, yes, there was a post. But if you want, just comment on the ppt
today or tomorrow and I can make the changes asap, since no one is probably
reading this in the next days :)

**Comment by SallyMcGrath** [comment]
> Hey Sally, yes, there was a post. But if you want, just comment on the ppt today or tomorrow and I can make the changes asap, since no one is probably reading this in the next days :)

OK great -- I've left a bunch of comments in the deck. It's basically the same comment over and over, which is that there's too much text on the slides. 30 words MAX.

**Comment by SallyMcGrath** [comment]
@kfklein15 just reminding you about this approved PR

**Pull request merged**
