### PR TITLE
Move windows instructions to Instructor page

### PR DESCRIPTION
**Pull request by ghost**
Moving the windows set up instructions from the preparation page to within the Instructors page

## What does this change?

Module: SQL
Week(s): All

## Description

Removing the Windows set up instructions from this page.

## Who needs to know about this?

@SallyMcGrath 
I hope I've done this right, this is my second edit so please educate me if I'm doing it wrong :)
#340 

## Rendered Pages

-----
[View rendered docs/db/prep.md](https://github.com/CodeYourFuture/syllabus/blob/ochthenoodle-moveWindows/docs/db/prep.md)

### CODE REVIEW

**Review by SallyMcGrath — COMMENTED** [review]
Hi @ochthenoodle  - can you add the instructor notes change to this PR and I'll nod them both through?

**Comment by ghost** [comment]
Hi @SallyMcGrath sorry I have no idea how to do that? When I clicked edit on the pages it gave me the option to create a pull request which I did following the instructions you sent last time, I didn't see an option to edit more things within the "interface" it then created. I've never used git before this and I'm not finding it easy to understand.

**Comment by SallyMcGrath** [comment]
This is actually fine as two PRs, @ochthenoodle ! I'll merge. Thanks so much!

**Comment by ghost** [comment]
Amazing thank you @SallyMcGrath sorry if I made it complicated!

**Comment by SallyMcGrath** [comment]
@all-contributors please add @ochthenoodle for content and code

**Pull request merged**
