### PR TITLE
Add Task Numbers to Class Exercises for Node

### PR DESCRIPTION
**Pull request by ChrisOwen101**
## What does this change?

Module: Node
Week(s): All

## Description

Added Task Numbers to make it easier to understand the flow of the lesson. 

For example

Before:
image

After:
image

### CODE REVIEW

**Comment by IsmaelMartinez** [comment]
Hi @ChrisOwen101 , will it not be possible to use the markdown ordered list on this? Using a `.` instead of a `)`. Then you can create a simple Table of Content if required/suitable

**Comment by ChrisOwen101** [comment]
The table of content is actually generated by Docusaurus so we don't need to worry about that so much :)

See [here](https://syllabus.codeyourfuture.io/node/week-1/lesson).

**Comment by IsmaelMartinez** [comment]
I see what you referring. The headers... and markdown doesn't support numbering in headers. So ignore my previous suggestion :) Let me know if you want me to go throw some of the pages... you got a few to modify!

**Review by alismith-dev — APPROVED** [review]
Happy to go with this as-is :shipit: 

But I wonder if the numbering is needed at all? I don't believe we use numbering in any other modules? Especially now we that we have the persistent ToC, the ordering I think is implicit?

**Pull request merged**
