### PR TITLE
Fix typo - description doesn't match variable name

### PR DESCRIPTION
**Pull request by Emiliecg**
## What does this change?

Module: Intro to Tests (?)
Week(s): JS1

## Checklist

- [x] I have read the [contributing guidelines](https://syllabus.codeyourfuture.io/contributing/overview)
- [ ] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [ ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [ ] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://syllabus.codeyourfuture.io/guides/code-style-guide)

## Description

Fixing a typo: The description of the code mentions a variable called `output`, but in the code it is called `result`.

### CODE REVIEW

**Review by gregdyke — APPROVED** [review]
Thanks!

**Comment by Emiliecg** [comment]
> Thanks!

Do I need to reach out to anyone about getting this merged, or can I let you take it from there? (first day :))

**Review by Dedekind561 — APPROVED** [review]
Good spot! LGTM

**Comment by Emiliecg** [comment]
> Good spot! LGTM

Just FYI I don't have write access so I will not be merging

**Pull request merged**
