### PR TITLE
PD-HTML/CSS

### PR DESCRIPTION
**Pull request by esma-g**
## What does this change?

Module: HTML/CSS
Week(s): 1, 2, 3, 4

## Description

- Deleted learning objectives
- Removed note for the facilitator
- Exercises’ markup changed to :::note markup
- Missing PD sections added to the contents table
- Formatted PD coursework with numbers
- Added session and exercise objectives
- Clarified instructions and concepts

## Who needs to know about this?

@kfklein15 @ElizabethlawalCYF @CodeYourFuture/syllabus

### CODE REVIEW

**Review by kfklein15 — DISMISSED** [review]
Approving it. But might be worth us getting feedback from of the PD Leaders (in the future) in the room to see if these instructions are clear enough for them and trainees.

**Comment by esma-g** [comment]
> Approving it. But might be worth us getting feedback from of the PD Leaders (in the future) in the room to see if these instructions are clear enough for them and trainees.

I have edited the content following a call with the PD volunteer for London10 who delivered this session last Saturday.

**Comment by esma-g** [comment]
Deleting PD learning objectives and not adding any new ones until they are re-created by the PD syllabus review.

**Review by kfklein15 — APPROVED** [review]
Ok

**Review by illicitonion — APPROVED** [review]

**Pull request merged**
