### PR TITLE
Added practice, reduced homework

### PR DESCRIPTION
**Pull request by gregdyke**
## What does this change?

Module: JS1
Week(s): Week 2

## Checklist

- [x] I have read the [contributing guidelines](https://syllabus.codeyourfuture.io/contributing/overview)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://syllabus.codeyourfuture.io/guides/code-style-guide)

## Description

Add material for flipped classroom

- practice exercises
- mentor guidance on what students should know and what recap material might look like
- reduce/realign homework

## Who needs to know about this?

@Dedekind561 @SallyMcGrath @Fatemeh-sadat-Torabi

### CODE REVIEW

**Comment by gregdyke** [comment]
Todo in the future: move fizzbuzz to the extra challenge or to the recap materials

**Review by Dedekind561 — APPROVED** [review]
LGTM. Thanks for putting together

**Comment by Dedekind561** [comment]
@gregdyke Would you like me to put together the videos for the practice sections, or did you already do those?

**Comment by gregdyke** [comment]
I plan to record this afternoon

**Pull request merged**
